name: Deploy

on:
push:
branches: ["main"]

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: SSH Deploy
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.SERVER_IP }}
      username: root
      key: ${{ secrets.SERVER_SSH_KEY }}
      script: |
        set -e
        APP_DIR=/root/projects/infinite-machine
        REPO_URL=https://github.com/naseerai/infinite-machine.git

        if [ ! -d "$APP_DIR/.git" ]; then
          git clone $REPO_URL $APP_DIR
        else
          cd $APP_DIR
          git reset --hard
          git pull origin main
        fi

        cd $APP_DIR
        docker compose up -d --build --remove-orphans
```
